name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Su dung nodejs 18

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
# Thêm Snyk để kiểm tra bảo mật
    - name: Install Snyk
      run: npm install -g snyk

    - name: Authenticate Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Run Snyk to check for vulnerabilities
      run: snyk test --severity-threshold=high --fail-on=never
# Thêm các bước liên quan đến Trivy
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.31.3/trivy_0.31.3_Linux-64bit.deb
        sudo dpkg -i trivy_0.31.3_Linux-64bit.deb
# Build Docker image
    - name: Build Docker Image
      run: docker build -t secure-app .

# Run Trivy to scan Docker image
    - name: Run Trivy to scan Docker image
      run: trivy image --exit-code 1 --severity HIGH,CRITICAL secure-app
